build:
	dotnet build
clean:
	dotnet clean
restore:
	dotnet restore
test:
	dotnet test
test-pact:
	dotnet test Todo.ContractTests
watch:
	dotnet watch run --project Todo.App
start:
	dotnet run --project Todo.App